{% set name = "autogluon.common" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/autogluon/autogluon/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 133ceb769cebce26255f379c129b58acacab2424a692b7ee81f02d78bbb228cb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install ./common -vv
  number: 0
  script_env:
    - RELEASE=1

requirements:
  host:
    - python {{ python_min }}
    - pip
  # see deps in https://github.com/autogluon/autogluon/blob/master/common/setup.py
  # version bounds are defined in https://github.com/autogluon/autogluon/blob/master/core/src/autogluon/core/_setup_utils.py
  run:
    - accelerate >=0.34.0,<2.0
    - autogluon.common ==1.5.0b20251219
    - autogluon.core ==1.5.0b20251219
    - autogluon.features ==1.5.0b20251219
    - autogluon.tabular ==1.5.0b20251219
    - chronos-forecasting >=2.2.2,<2.4
    - coreforecast >=0.0.12,<0.0.17
    - einops >=0.7,<1
    - fugue >=0.9.0
    - gluonts >=0.15.0,<0.17
    - lightning >=2.5.1,<2.6
    - mlforecast >=0.14.0,<0.15.0
    - networkx >=3.0,<4
    - orjson >=3.9,<4.dev0
    - peft >=0.13.0,<0.18
    - pytorch >=2.6,<2.10
    - scipy >=1.5.4,<1.17
    - statsforecast >=1.7.0,<2.0.2
    - tensorboard >=2.9,<3
    - transformers >=4.51.0,<4.58
    - utilsforecast >=0.2.3,<0.2.12
    - python >={{ python_min }},<3.13
    - numpy >=1.25.0,<2.4.0
    - pandas >=2.0.0,<2.4.0
    - boto3 <2,>=1.10
    - psutil <7.1.0,>=5.7.3
    - tqdm >=4.38,<5
    - requests
    - joblib >=1.2,<1.7
    # Constrain pyarrow to avoid ABI incompatibility with libabseil
    # pyarrow >=19.0.0 requires newer libabseil that causes symbol conflicts
    - pyarrow >19.0.0,<21.0.0
    - setuptools
    - packaging

test:
  imports:
    - autogluon.common
  commands:
    - python -c "from autogluon.common import __version__ as v; from packaging.version import parse; expected = '{{ version }}'; assert parse(v) == parse(expected), f'{v} != {expected}'"
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/autogluon.common
  summary: AutoML for Image, Text, and Tabular Data
  description: |
    AutoGluon automates machine learning tasks enabling you to easily achieve strong 
    predictive performance in your applications. With just a few lines of code, you 
    can train and deploy high-accuracy machine learning and deep learning models on 
    image, text, time series, and tabular data.  
  dev_url: https://github.com/autogluon/autogluon/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - suzhoum
    - tonyhoo
    - Innixma
    - prateekdesai04
