{% set name = "autogluon.common" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/autogluon/autogluon/archive/refs/tags/v{{ version }}.tar.gz 
  sha256: 5e9ddeb6c3ca06e10addb17f867e34c5e169d13ae46e704c16b798257718f1ba 

build:
  noarch: python
  script: {{ PYTHON }} -m pip install ./common -vv
  number: 0
  script_env:
    - RELEASE=1

requirements:
  host:
    - python >=3.9,<3.13
    - pip
  # see deps in https://github.com/autogluon/autogluon/blob/master/common/setup.py
  # version bounds are defined in https://github.com/autogluon/autogluon/blob/master/core/src/autogluon/core/_setup_utils.py
  run:
    - python >=3.9,<3.13
    - numpy <2.1.4,>=1.21
    - pandas <2.3.0,>=2.0.0
    - boto3 <2,>=1.10
    - psutil <7.0.0,>=5.7.3
    - tqdm <5,>=4.38
    - setuptools
    - packaging

test:
  imports:
    - autogluon.common
  commands:
    - python -c "from autogluon.common import __version__ as v; from packaging.version import parse; expected = '{{ version }}'; assert parse(v) == parse(expected), f'{v} != {expected}'" 
  requires:
    - pip

about:
  home: https://pypi.org/project/autogluon.common
  summary: AutoML for Image, Text, and Tabular Data
  description: |
    AutoGluon automates machine learning tasks enabling you to easily achieve strong 
    predictive performance in your applications. With just a few lines of code, you 
    can train and deploy high-accuracy machine learning and deep learning models on 
    image, text, time series, and tabular data.  
  dev_url: https://github.com/autogluon/autogluon/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - suzhoum
    - tonyhoo
    - giswqs
    - Innixma
    - prateekdesai04 
