{% set name = "autogluon.common" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://autogluon.s3.us-west-2.amazonaws.com/tarballs/1.1.1_patch/tarball.tar.gz 
  sha256: e8a23ffc2941e36cf239c472d1fba00a5f660c49a7035c3e6ef1a3a28dd284ea 

build:
  noarch: python
  script: {{ PYTHON }} -m pip install ./common -vv
  number: 3
  script_env:
    - RELEASE=1

requirements:
  host:
    - python >=3.8,<3.13
    - pip
  # see deps in https://github.com/autogluon/autogluon/blob/master/common/setup.py
  # version bounds are defined in https://github.com/autogluon/autogluon/blob/master/core/src/autogluon/core/_setup_utils.py
  run:
    - python >=3.8,<3.13
    - numpy <1.29,>=1.21
    - pandas <2.3.0,>=2.0.0
    - boto3 <2,>=1.10
    - psutil <6,>=5.7.3
    - tqdm <5,>=4.38
    - setuptools
    - packaging

test:
  imports:
    - autogluon.common
  commands:
    - python -c "from autogluon.common import __version__ as v; assert v == '{{ version }}', f'{v} != {{ version }}'"
  requires:
    - pip

about:
  home: https://pypi.org/project/autogluon.common
  summary: AutoML for Image, Text, and Tabular Data
  description: |
    AutoGluon automates machine learning tasks enabling you to easily achieve strong 
    predictive performance in your applications. With just a few lines of code, you 
    can train and deploy high-accuracy machine learning and deep learning models on 
    image, text, time series, and tabular data.  
  dev_url: https://github.com/autogluon/autogluon/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - suzhoum
    - tonyhoo
    - giswqs
    - Innixma
    - prateekdesai04 
